### ISSUE TITLE
Hamming codes for 8,4

### ISSUE THREAD

**Issue by duartemolha** [mdshw5/hamstring#1]
If I understood correctly your software generates barcodes of length 7. Do you plan on supporting creating larger barcodes?
Thanks

**Comment by mdshw5** [comment]
I'd love to support creating longer barcodes, but don't use this project actively anymore. If you want to make a pull request that would be great, or if you can describe the logic for generalizing the barcodes to different lengths I would be glad to tackle the implementation. 

I've just done a quick search (since I haven't been thinking about sequence edit distances for about 5 years) and see that there is a `DNAbarcodes` package for Rlang that might be useful to you. It also appears that the Hamming8,4 encoding is implemented in C++ https://github.com/LarT2P/StikerP/blob/7d4f0bd6586eefddebb0070364754847665c4826/BHumanCodeRelease-master/Src/Tools/HammingEncodingBase4.cpp#L77

If I have some time I'll see if I can add the Hamming8,4 encoding and decoding to this project.

**Comment by mdshw5** [comment]
I've added support for Hamming8,4 codes in https://github.com/mdshw5/hamstring/releases/tag/v1.1. It's also on PyPI now.

**Comment by duartemolha** [comment]
Hey... thanks you for both your comments and the implementation I am sure to test it. ;)
